load("//graphql/internal:router.bzl", "ROUTER_REPOSITORY")
load("//graphql/internal:rover.bzl", "ROVER_REPOSITORY")
load("//shared:toolchains_repo.bzl", "toolchains_repo")

def _binary_repo_impl(ctx):
    ctx.download_and_extract(ctx.attr.url.format(
        version = ctx.attr.version,
    ), stripPrefix = "dist")

    ctx.file(
        "BUILD.bazel",
        content = """# Autogenerated by graphql/internal:router.bzl
load("@com_github_tomsons_rules_graphql//graphql:toolchains.bzl", "{toolchain_name}")

{toolchain_name}(
    name = "toolchain",
    toolchain = ":{binary_name}",
    version = "{version}",
)
        """.format(
            version = ctx.attr.version,
            toolchain_name = ctx.attr.toolchain_name,
            binary_name = ctx.attr.binary_name,
        ),
    )


binary_repo = repository_rule (
    implementation = _binary_repo_impl,
    attrs = {
        "version": attr.string(mandatory = True),
        "url": attr.string(mandatory = True),
        "toolchain_name": attr.string(mandatory = True),
        "binary_name": attr.string(mandatory = True),
    },
)

def graphql_register_toolchains(
    rust_router_version = "1.24.0",
    rover_cli_version = "0.16.0",
):
    meta = {}
    for key, value in ROUTER_REPOSITORY.items():
        binary_repo(
            name = "router_{}".format(key),
            version = rust_router_version,
            url = value['url'],
            toolchain_name = "router_toolchain",
            binary_name = "router",
        )
        meta[key] = value["exec_compatible_with"]

        native.register_toolchains("@router_toolchains//:{}".format(key))
    toolchains_repo(
        name = "router_toolchains",
        repository_name = "router",
        toolchain_name = "toolchain",
        root_repository_name = "com_github_tomsons_rules_graphql",
        toolchain_type_name = "router_toolchain",
        meta = meta,
    )
    meta2 = {}
    for key, value in ROVER_REPOSITORY.items():
        binary_repo(
            name = "rover_{}".format(key),
            version = rover_cli_version,
            url = value['url'],
            toolchain_name = "rover_toolchain",
            binary_name = "rover",
        )
        meta2[key] = value["exec_compatible_with"]

        native.register_toolchains("@rover_toolchains//:{}".format(key))
    toolchains_repo(
        name = "rover_toolchains",
        repository_name = "rover",
        toolchain_name = "toolchain",
        root_repository_name = "com_github_tomsons_rules_graphql",
        toolchain_type_name = "rover_toolchain",
        meta = meta2,
    )